# This is the config file
title: Suzannah Rowntree
description: > # this means to ignore newlines
  Suzannah Rowntree - author
url: https://suzannahrowntree.site
enforce_ssl: suzannahrowntree.site
baseurl: ""

# Build settings
markdown: kramdown

collections:
  books:

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
